<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ProductName</name>
   <tag></tag>
   <elementGuidId>522a1725-b188-4d35-90c3-1ef7f558e820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1[@class = 'product-single-name' and (text() = '${ProductName}' or . = '${ProductName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.product-single-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/main/div[2]/div[2]/div/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>aaeb3e97-031e-4a2b-a85e-de0cc4eca652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-single-name</value>
      <webElementGuid>f5d31861-c4cc-4aca-a747-9c7d9e30f893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${ProductName}</value>
      <webElementGuid>4f3af7df-2ff2-4ccf-ba6b-f96ca807947f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;product-detail&quot;]/div[@class=&quot;product-page-middle page-width&quot;]/div[@class=&quot;grid grid-cols-1 gap-3 md:grid-cols-2&quot;]/div[2]/div[@class=&quot;flex flex-col gap-1&quot;]/h1[@class=&quot;product-single-name&quot;]</value>
      <webElementGuid>6739daa2-7753-4f0c-978c-b85f7371fb83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div[2]/div[2]/div/div[2]/div/h1</value>
      <webElementGuid>ef2a9b05-b25d-42af-a965-47cc4687eeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nike Air Zoom Pegasus 35'])[2]/following::h1[1]</value>
      <webElementGuid>61398f19-1347-46e4-ac89-6f1f66a815f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[2]/following::h1[1]</value>
      <webElementGuid>27abfe31-8e06-47cd-b249-88aa53d36da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$452.10'])[1]/preceding::h1[1]</value>
      <webElementGuid>bd44b1aa-43a6-4f7d-8c26-cb538d1575ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nike air zoom pegasus 35']/parent::*</value>
      <webElementGuid>d6b16c40-8f78-4e7f-a192-097bf8df3b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>51c490b1-5369-46fc-997d-8af67740b1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Nike air zoom pegasus 35' or . = 'Nike air zoom pegasus 35')]</value>
      <webElementGuid>65be863f-c5b0-4ea6-8eac-fafd0e1154e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
