<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telephone</name>
   <tag></tag>
   <elementGuidId>a808fd67-dd32-4f09-b8a9-6d8b6b4e932d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;address[telephone]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@placeholder='Telephone'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65e45448-bbe6-4de4-b9cc-d96df29be0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a35f7b02-ba2b-4e55-b958-28ebcc7ac407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[telephone]</value>
      <webElementGuid>2c5ed495-1355-407b-b5e0-147c1f95a97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Telephone</value>
      <webElementGuid>8855cb54-2c66-4fb9-96dd-bc510bf7ecfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkoutShippingAddressForm&quot;)/div[1]/div[@class=&quot;grid grid-cols-2 gap-1&quot;]/div[2]/div[@class=&quot;form-field-container null&quot;]/div[@class=&quot;field-wrapper flex flex-grow&quot;]/input[1]</value>
      <webElementGuid>2a7fc328-ba9e-432e-b1b0-4e8e5da6bb18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='address[telephone]']</value>
      <webElementGuid>5a0ca30c-4f26-425e-b0e0-134f37ffdb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutShippingAddressForm']/div/div/div[2]/div/div/input</value>
      <webElementGuid>cd82b275-d9a5-484d-8387-b64565469384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0e5d8fa4-7a7a-44bf-9c55-cffc0e37ff5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address[telephone]' and @placeholder = 'Telephone']</value>
      <webElementGuid>073343d2-1cc0-4f9f-8faf-cece9094617c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
