<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Province</name>
   <tag></tag>
   <elementGuidId>3a73a2f1-d63e-48b8-8a84-a47e7e14b25c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='address[province]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98d0cd6f-2e2d-4439-a87a-cbec69875754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field</value>
      <webElementGuid>369b4bda-9221-4e99-95e0-db82111bd0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address[province]</value>
      <webElementGuid>7f20ba5a-b9c0-466a-9dd7-bc528e864556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address[province]</value>
      <webElementGuid>e5e88483-93e0-46d2-89e3-446704c4e4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Province</value>
      <webElementGuid>8a6834dd-46fc-4f31-9712-b0dd6468df0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProvinceAnhuiBeijingChongqingFujianGansuGuangdongGuangxiGuizhouHainanHebeiHeilongjiangHenanHubeiHunanJiangsuJiangxiJilinLiaoningNei MongolNingxiaQinghaiShaanxiShandongShanghaiShanxiSichuanTianjinXinjiangXizangYunnanZhejiang</value>
      <webElementGuid>7affe5a6-3982-4cb4-b1e4-dc54b2d84c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address[province]&quot;)</value>
      <webElementGuid>98b35cee-9ea9-4f16-a4fa-911aac4d15f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='address[province]']</value>
      <webElementGuid>e41dc2e0-23e2-415e-9dda-0f6c82c8754e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkoutShippingAddressForm']/div/div[5]/div/div/div/select</value>
      <webElementGuid>df25228b-3085-41fb-8f48-0363f32f440a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::select[1]</value>
      <webElementGuid>fcea78d1-c3f7-4a66-ad9b-21b9d8657944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>3fa6c2ee-e86b-491f-ad6f-1da53d38b06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postcode'])[1]/preceding::select[1]</value>
      <webElementGuid>dc0f070d-d3c0-4f1c-b5df-08447ec3addf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Method'])[1]/preceding::select[1]</value>
      <webElementGuid>1d1cd1b9-807f-4efc-a11d-9fc3da6f10d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/select</value>
      <webElementGuid>e4536160-6de5-4b4c-81a9-01638e28d677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'address[province]' and @name = 'address[province]' and @placeholder = 'Province' and (text() = 'ProvinceAnhuiBeijingChongqingFujianGansuGuangdongGuangxiGuizhouHainanHebeiHeilongjiangHenanHubeiHunanJiangsuJiangxiJilinLiaoningNei MongolNingxiaQinghaiShaanxiShandongShanghaiShanxiSichuanTianjinXinjiangXizangYunnanZhejiang' or . = 'ProvinceAnhuiBeijingChongqingFujianGansuGuangdongGuangxiGuizhouHainanHebeiHeilongjiangHenanHubeiHunanJiangsuJiangxiJilinLiaoningNei MongolNingxiaQinghaiShaanxiShandongShanghaiShanxiSichuanTianjinXinjiangXizangYunnanZhejiang')]</value>
      <webElementGuid>ec2bfdec-5669-4366-b3c0-d6f7962a1f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
