<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>checkout-login-default</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8ee29688-f5f0-40ff-b914-08638771af09</testSuiteGuid>
   <testCaseLink>
      <guid>d9669850-ec9a-41cf-a735-43c20524e6e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REUSABLE TEST CASE/TC00 - OPEN BROWSER</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2a1ea87b-a8c2-4974-8be7-ba71c90c49f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REUSABLE TEST CASE/TC02 - LOGIN PAGE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12ac199d-2b2c-43eb-8e9d-7ba8d35586b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46886a4f-6749-4480-b6db-fdabfe88c3be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6dda11d9-f515-43df-8c16-94c6768d6817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REUSABLE TEST CASE/TC03 - PICK PRODUCT - HOMEPAGE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>283aa15d-0a54-46d8-8c75-ccd74bfc98df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feeca625-a58c-4686-a98e-f86dbd988acf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d23da73-5935-45e5-810d-bbd0eb2e8f7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95eb192-ea5b-422f-ba37-6e36d5b7956a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4849e55-7845-49e1-86af-f40a7e7fe6eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REUSABLE TEST CASE/TC04 - ADD TO CART - SHOPPING CART</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>639d89e6-fbb0-492c-9013-657efadbb3d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REUSABLE TEST CASE/TC05 - CHECK OUT PAGE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39ab782c-ea04-4fd5-8290-a1d4cec354ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f26a96b0-bd6a-4256-a49d-2dc1c7ba0e2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76aa641b-b6a4-4267-97d3-4d2c7a7d7eee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcfed460-e09c-4bfb-ab64-b23be71bfa90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a9edeed-391c-4af0-b18e-c4555b3d3207</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e6d8f06-185a-489b-8fd4-7616a66be3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1db29c7-48bb-4040-96ae-32a7978e1b9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f22639e2-1ada-4dbe-939a-f9b9a5942255</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43ff3811-14d7-4013-9954-07f78c47f453</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb75b56e-b6a6-40a6-847b-acc0485d53c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3488fef5-479b-4c63-8d38-1335c2b35e71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f835fc61-a7af-4fba-98a7-b118661e13d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/REUSABLE TEST CASE/TC06 - PAYMENT PAGE</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4499e12b-c8c8-4395-bc04-c17d4dc2bf38</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
