<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_label</name>
   <tag></tag>
   <elementGuidId>57d2a3db-6ee5-4f82-9b97-c38fa7557426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[normalize-space()='Login'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7c844a4-8891-4e6c-8633-d174c1989f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-interactive hover:underline</value>
      <webElementGuid>228ef043-2c44-4d52-8cba-b07c2af92e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/login</value>
      <webElementGuid>dfa42097-1f47-4ad0-b037-32ad1a0b0ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>87d43323-7d71-4050-9f3f-69fa82e6e879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/main[@class=&quot;content&quot;]/div[@class=&quot;page-width grid grid-cols-1 md:grid-cols-2 gap-3&quot;]/div[1]/div[@class=&quot;checkout-steps&quot;]/div[@class=&quot;checkout-contact checkout-step&quot;]/div[1]/div[@class=&quot;mb-1&quot;]/a[@class=&quot;text-interactive hover:underline&quot;]</value>
      <webElementGuid>70e800fd-bf33-4a60-8900-1b231de09caf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>df886263-6b16-418f-b071-a426afeed650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>b93ff254-27db-480a-9234-9399e5174f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already have an account?'])[1]/following::a[1]</value>
      <webElementGuid>237c30d1-f01d-4841-87ae-308719a46aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact information'])[2]/following::a[1]</value>
      <webElementGuid>e0d61745-a808-49c7-9967-f9db4fff3cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to shipping'])[1]/preceding::a[1]</value>
      <webElementGuid>203d3b29-7bf9-4d95-a6ac-958d1cd35e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nike air zoom pegasus 35'])[1]/preceding::a[1]</value>
      <webElementGuid>78b46022-9499-4ae7-aa5b-47f044254632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>32c6df88-ed39-4dde-a540-e1ac9f4102d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/account/login')])[2]</value>
      <webElementGuid>eb8da799-ec3d-4bf2-88d5-5e6f0918afde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>6ff562b3-7a8c-4335-9737-c6a5de199db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/login' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>623ba6f0-2b11-4659-9e96-4d29c162ff88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
